plugin:
    name: 'luismayta.devops::lang.plugin.name'
    description: 'luismayta.devops::lang.plugin.description'
    author: 'Luis Mayta'
    icon: oc-icon-adjust
    homepage: ''
navigation:
    main-menu-item:
        label: Devops
        url: luismayta/devops/peliculascontroller
        icon: icon-life-ring
        sideMenu:
            side-menu-item:
                label: 'Menu Item'
                icon: icon-sitemap
                url: /
